### ISSUE TITLE
Generate alternate version of README.md for DevSite

### ISSUE THREAD

**Issue by camiekim** [GoogleCloudPlatform/eventarc-samples#10]
Pls create another version of the README file for DevSite using the following example as a guide, thanks:

## Using Pub/Sub

Requests to your service are triggered by messages published to a Pub/Sub topic.
For more information, see [Creating a trigger](/eventarc/docs/creating-triggers.md).

### Custom applications
- Any custom application that can publish to a Pub/Sub topic

### BigQuery (scheduled queries)
- `bigquery.googleapis.com` ([more info](/bigquery/docs/scheduling-queries))

### Cloud Asset
- `cloudasset.googleapis.com` ([more info](/asset-inventory/docs/monitoring-asset-changes))

## Using Cloud Audit Logs

These `serviceName` and `methodName values` can be used to create the filters for Eventarc triggers. For more information, see [Creating a trigger](/eventarc/docs/creating-triggers.md).

#### `serviceName`

- `accessapproval.googleapis.com`

#### `methodName`

- `google.cloud.accessapproval.v1.AccessApproval.ApproveApprovalRequest`
- `google.cloud.accessapproval.v1.AccessApproval.DeleteAccessApprovalSettings`
- `google.cloud.accessapproval.v1.AccessApproval.DismissApprovalRequest`
- `google.cloud.accessapproval.v1.AccessApproval.UpdateAccessApprovalSettings`

**Comment by camiekim** [comment]
Looks really good, Mete. See https://cloud.devsite.corp.google.com/eventarc/docs/reference/supported-events

A couple of things:

1. Could you change the first paragraph to: 

"Requests to your service, or any custom application that can publish to a Pub/Sub
topic, are triggered by messages published to a Pub/Sub topic. For more information, see [Creating a trigger](/eventarc/docs/creating-triggers.md)."

2. Could you link the headings instead of using "more info", like this:

###[BigQuery (scheduled queries)](/bigquery/docs/scheduling-queries)
- `bigquery.googleapis.com`

thanks!

**Comment by meteatamel** [comment]
Hi Camie, I changed the headings and also removed the code formatting. As a bonus, I also display "Custom applications" first in the list, as it's a specific case. Please re-open the bug if any other issues.
