### ISSUE TITLE
Regenerate events to have a unique link

### ISSUE THREAD

**Issue by minyu19** [GoogleCloudPlatform/eventarc-samples#136]
Currently event types that are common to Direct and CAL events are differentiated with a "preview" on the links. For ex: "Cloud Data Fusion" has the link https://cloud.google.com/eventarc/docs/event-types#cloud-data-fusion-preview and https://cloud.google.com/eventarc/docs/event-types#cloud-data-fusion. Considering that these events will GA eventually and the preview tags will be removed, we have to regenerate the events so that the links are unique.

**Comment by meteatamel** [comment]
The links are generated by DevSite (not events generator) and they're indeed unique. As an example, you can check out Pub/Sub with its 2 unique links for direct and CAL events:

https://cloud.google.com/eventarc/docs/event-types#cloud-pubsub
https://cloud.google.com/eventarc/docs/event-types#cloud-pubsub_1

Nothing to fix here in events generator, so closing it now.
