### ISSUE TITLE
docs: Automate generation of events (/eventarc-events/EventListGenerator)

### ISSUE THREAD

**Issue by camiekim** [GoogleCloudPlatform/eventarc-samples#49]
For atamel@ per b/212864274

**Comment by meteatamel** [comment]
Hi Camie, I automated generation of events. [README.md](https://storage.googleapis.com/events-atamel-event-list-generator/README.md) and [README_devsite.md](https://storage.googleapis.com/events-atamel-event-list-generator/README_devsite.md) are automatically generated every day at 9am and saved in a public bucket.
