### ISSUE TITLE
unsupported destination

### ISSUE THREAD

**Issue by cedric-orange** [GoogleCloudPlatform/eventarc-samples#51]
with:

```
gcloud eventarc triggers create $TRIGGER_NAME \
  --location=us-central1 \
  --destination-workflow=$WORKFLOW_NAME \
  --destination-workflow-location=us-central1 \
```

I have got an error:

```
ERROR: (gcloud.eventarc.triggers.create) INVALID_ARGUMENT: The request was invalid: unsupported destination: 
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - field: trigger.destination
- '@type': type.googleapis.com/google.rpc.RequestInfo
  requestId: 6ed18531496b8e99
```

In documentation and command help I can't see any information about this option : `--destination-workflow`

**Comment by meteatamel** [comment]
Hi, `--destionation-workflow` is currently private preview. I think you missed the following warning at the top?

Note: Eventarc Workflows destination is currently a feature in private preview. Only allow-listed projects can currently take advantage of it. Please fill out this form to get your project allow-listed before attempting this sample.

**Comment by meteatamel** [comment]
Closing this. Feel free to comment or reopen.
