### ISSUE TITLE
Recieve error when running command 

### ISSUE THREAD

**Issue by JoelGoodman19** [GoogleCloudPlatform/eventarc-samples#52]
When running command in processing pipelines
 docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME -f image-v2/$SERVICE_NAME/csharp/Dockerfile .

Receive Error:
Step 3/11 : COPY image-workflows/filter ./image/filter
COPY failed: file not found in build context or excluded by .dockerignore: stat image-workflows/filter: file does not exist

**Comment by meteatamel** [comment]
Thanks for reporting. We forgot to change Dockerfiles when renamed the folders. It should work now.

**Comment by meteatamel** [comment]
I just re-tested and it works for me. Could you please make sure you synced to the latest code and paste the full command and the output?
