### ISSUE TITLE
custom-events: setup.sh script returning a NOT_FOUND for channels.create method

### ISSUE THREAD

**Issue by guilhem-martin** [GoogleCloudPlatform/eventarc-samples#64]
When I run the _setup.sh_ script within Cloud Shell, I get an error for the channel creation:

`ERROR: (gcloud.eventarc.channels.create) NOT_FOUND: Method not found.`

Note: the `cloud run` creation is working fine in the _setup.sh_ script.

**Comment by meteatamel** [comment]
Do you have your project allow-listed?

**Comment by meteatamel** [comment]
Hi @guilhem-martin, I'm closing this bug but feel free to reopen if the issue still persists.
