### ISSUE TITLE
Event list generator: Remove Pub/Sub events

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/eventarc-samples#81]
Currently, we list the following events under Pub/Sub:

## Using Pub/Sub

Requests to your service are triggered by messages published to a Pub/Sub topic.
For more information, see [All trigger targets](/eventarc/docs/targets.md).

### Custom applications

- Any custom application that can publish to a PubSub topic

### [Artifact Registry](https://cloud.google.com/artifact-registry/docs/configure-notifications)

- `artifactregistry`

### [BigQuery (scheduled queries)](https://cloud.google.com/bigquery/docs/scheduling-queries)

- `bigquery.googleapis.com`

### [Cloud Asset](https://cloud.google.com/asset-inventory/docs/monitoring-asset-changes)

- `cloudasset.googleapis.com`

### [Cloud Billing](https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications)

- `cloudbilling.googleapis.com`

### [Cloud Build](https://cloud.google.com/build/docs/subscribe-build-notifications)

- `cloudbuild.googleapis.com`

### [Cloud Healthcare](https://cloud.google.com/healthcare/docs/how-tos/pubsub)

- `healthcare.googleapis.com`

### [Cloud IoT](https://cloud.google.com/iot/docs/how-tos/mqtt-bridge#publishing_telemetry_events_to_additional_cloud_pubsub_topics)

- `cloudiot.googleapis.com`

### [Cloud Scheduler](https://cloud.google.com/scheduler/docs/creating)

- `cloudscheduler.googleapis.com`

### [Cloud Source Repositories](https://cloud.google.com/source-repositories/docs/pubsub-notifications)

- `sourcerepo.googleapis.com`

### [Cloud Storage](https://cloud.google.com/storage/docs/pubsub-notifications)

- `storage.googleapis.com`

### [Container Registry](https://cloud.google.com/container-registry/docs/configuring-notifications)

- `containerregistry`

I suggest we remove all the services that have integration to Pub/Sub (these do not show up in the UI and potentially confusing to users).

**Comment by meteatamel** [comment]
The next question is, what do we do with Pub/Sub `google.cloud.pubsub.topic.v1.messagePublished`? I suggest we move that under `Directly from a Google Cloud source` section

**Comment by camiekim** [comment]
That's a great idea, Mete. Thanks!

**Comment by meteatamel** [comment]
Fixed
