### ISSUE TITLE
Event list generator: Make it consistent with the UI

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/eventarc-samples#82]
Right now, the event list has the following format:

* Directly from a Google Cloud source
  * Cloud Storage 
    * google.cloud.storage.object.v1.archived
* Using Cloud Audit Logs
  * Cloud Storage 
    * storage.buckets.create
* Using Pub/Sub
* Using third-party sources

On the other hand, the Google Cloud console has the following format:

* First-party
  * Cloud Storage
    * Direct
      *  google.cloud.storage.object.v1.archived
    * via Cloud Audit Logs  
      * storage.buckets.create 
* Custom
* Third-party

**Comment by meteatamel** [comment]
I like the latter as it's always event source -> event medium -> event and there's a single place to look for each event source (eg. Cloud Storage). Should we consider changing our event list format to match the UI?

**Comment by camiekim** [comment]
Yes, I'm fine with this and think it's a good idea to be in sync with the console. Note that we're not supposed to use "via" in the docs so unless the console can change, we'll work around that in any related pages or content.

**Comment by meteatamel** [comment]
Hi @camiekim, I looked into this and it's actually more involved than I thought. I'll park it for now but let me know if you think it's important to match the format of docs with the console and I'll spend more time on it.

**Comment by camiekim** [comment]
Ok.

**Comment by meteatamel** [comment]
I'm closing this as Won't Fix
