### ISSUE TITLE
Create a diff between output generations

### ISSUE THREAD

**Issue by camiekim** [GoogleCloudPlatform/eventarc-samples#84]
Would it be possible to output a file that shows the difference from one generation of the event types to the next? Or, if that's not feasible, could we retain at least two generations of the output so that they could be compared using a diff tool?

**Comment by meteatamel** [comment]
If you click on the files and see history, you can see the commits to the file and that commit basically gives you a diff. Here's an example: https://github.com/GoogleCloudPlatform/eventarc-samples/commit/837dc50c8fb6995911534f3475654bbe616a8683

Would this be sufficient?

**Comment by camiekim** [comment]
Yes, that works well, thanks.
