### ISSUE TITLE
Tutorial: Image processing pipeline v3 issues

### ISSUE THREAD

**Issue by willisc7** [GoogleCloudPlatform/eventarc-samples#94]
I ran into two issues on Step 10 of this code lab: https://codelabs.developers.google.com/codelabs/cloud-event-driven-orchestration#9

1. Under "One time setup" section, there is a step that uses `PROJECT_NUMBER` when it should use `PROJECT_ID`.
2. The "Create" section command fails with the following error:
    ```
    ERROR: (gcloud.eventarc.triggers.create) PERMISSION_DENIED: Permission "eventarc.events.receiveEvent" denied on 
    "image-processing-sa@workflows-codelab-0.iam.gserviceaccount.com"
    - '@type': type.googleapis.com/google.rpc.RequestInfo
    requestId: 18ea5fa999928824
    ```
    I needed to run the following command first in order to get it to work:
    ```
    gcloud projects add-iam-policy-binding $PROJECT_ID \
    --member serviceAccount:$SERVICE_ACCOUNT@$PROJECT_ID.iam.gserviceaccount.com \
    --role roles/eventarc.eventReceiver
    ```

**Comment by meteatamel** [comment]
Thanks a lot @willisc7 for opening the bug with actionable feedback! I tested and updated the underlying tutorial in this repo on GitHub with your feedback. I'm also updating the codelab and you can keep track of that in this bug: https://github.com/googlecodelabs/feedback/issues/1165

**Comment by meteatamel** [comment]
Closing this bug now as the repo is updated. Please follow 1165 for updates on the codelab. Thanks again!
