### ISSUE TITLE
"Cloud Deployment Manager" should be "Cloud Deploy"

### ISSUE THREAD

**Issue by camiekim** [GoogleCloudPlatform/eventarc-samples#97]
"Cloud Deployment Manager" is being output as a heading twice. The first instance should be "Cloud Deploy".

**Comment by meteatamel** [comment]
Hi @camiekim, we pull in AuditLog events from another repo from this file: https://raw.githubusercontent.com/googleapis/google-cloudevents/master/json/audit/service_catalog.json

So, it needs to be fixed there. Not sure who's in charge of that repo though.

**Comment by meteatamel** [comment]
I'm closing this as we can't do anything in this repo. I suggest you reach out to the folks in  google-cloudevents repo

**Comment by camiekim** [comment]
Ok, thanks, Mete. Opened an issue here: https://github.com/googleapis/google-cloudevents/issues/441

**Comment by averikitsch** [comment]
Once https://github.com/googleapis/google-cloudevents/issues/441 is merged, then the generator can be run again.

**Comment by meteatamel** [comment]
Verified that the events list is generated with "Cloud Deploy now". Closing it.
